nelmio_security:

    csp:
        enforce:
            level1_fallback: false
            browser_adaptive:
                enabled: false
            report-uri: '%router.request_context.base_url%/nelmio/csp/report'
            default-src:
                - 'self'
            script-src:
                - 'self'
                - 'data:'
                - 'unsafe-inline'
                - 'blob:'
                - 'https://ga.jspm.io/npm:es-module-shims@1.8.2/dist/es-module-shims.js'
            style-src:
                - 'self'
                - 'unsafe-inline'
            img-src:
                - 'self'
                - 'data:'
                - 'https://api.dicebear.com'
            connect-src:
                - 'self'
            frame-src:
                - 'https://www.openstreetmap.org'
                - 'self'
            block-all-mixed-content: true

    # prevents framing of the entire site
    clickjacking:
        paths:
            '^/.*': DENY

    # disables content type sniffing for script resources
    content_type:
        nosniff: true

    # forces Microsoft's XSS-Protection with
    # its block mode
    xss_protection:
        enabled: true
        mode_block: true

    # Send a full URL in the `Referer` header when performing a same-origin request,
    # only send the origin of the document to secure destination (HTTPS->HTTPS),
    # and send no header to a less secure destination (HTTPS->HTTP).
    # If `strict-origin-when-cross-origin` is not supported, use `no-referrer` policy,
    # no referrer information is sent along with requests.
    referrer_policy:
        enabled: true
        policies:
            - 'no-referrer'
            - 'strict-origin-when-cross-origin'
